"""created verifications model

Revision ID: 35ee80b50e49
Revises: 9024c531b2fd
Create Date: 2024-06-30 13:27:18.268497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ee80b50e49'
down_revision = '9024c531b2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
