"""created requestloan model, made modifications to Verifications and Loan model

Revision ID: 4ec65136cbca
Revises: 35ee80b50e49
Create Date: 2024-07-01 12:48:13.866068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec65136cbca'
down_revision = '35ee80b50e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('request_loan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_requestloan_id', 'requestloans', ['request_loan_id'], ['id'])

    with op.batch_alter_table('requestloans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=3), nullable=False))
        batch_op.add_column(sa.Column('approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_requested', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('amortization_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='amortizationtypeenum'), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.alter_column('bvn',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.alter_column('bvn',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('requestloans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('amortization_type')
        batch_op.drop_column('date_requested')
        batch_op.drop_column('approval')
        batch_op.drop_column('amount')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_loan_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
