name: Trustlend API Github Action Workflow

on:
    push:
      branches:
        - dev
    pull_request:
       types:
         - closed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 2
        matrix:
          python-version: [3.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run migrations
        run: |
          flask db init || true
          flask db migrate -m "Initial migration"
          flask upgrade

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Run tests
        run: |
          pytest tests